services:
  db:
    image: postgres:17-alpine
    container_name: vitae-db
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-vitae}
    volumes:
        - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  db_data: